<AccountList>
    on_pre_enter: root.loadAccountList()
    BoxLayout:
        orientation: 'vertical'
        Label:
            text: '계정 목록'
            font_size: '30dp'
        BoxLayout:
            Label:
                text: '주소'
            Label:
                text: '아이디'
            Label:
                text: '비밀번호'
        ScrollView:
            size_hint_y: 0.2
            do_scroll_x: False
            do_scroll_y: True
            GridLayout:
                id: accountList
                cols: 3
                size_hint_y: None
                height: self.minimum_height
        BoxLayout:
            size_hint_y: 0.4
            Button:
                text: '계정 추가'
                on_press: root.createAccount()
            Button:
                text: '계정 삭제'
                on_press: root.deleteAccount()
        BoxLayout:
            size_hint_y: 0.4
            Button:
                text: '비밀번호 생성'
                on_press: root.generatePassword()
            Button:
                text: '비밀번호 설정'
                on_press: root.manager.current = 'pswdSettings'
