<PswdSettings>:
    BoxLayout:
        orientation: 'vertical'
        Label:
            text: '비밀번호 설정'
            font_size: '30dp'
        BoxLayout:
            Label:
                text: '필수문자 : '
            GridLayout:
                cols: 2
                ToggleButton:
                    id: upperToggle
                    text: '대문자'
                ToggleButton:
                    id: lowerToggle
                    text: '소문자'
                ToggleButton:
                    id: numberToggle
                    text: '숫자'
                ToggleButton:
                    id: specialToggle
                    text: '특수문자'
        BoxLayout:
            Label:
                text: '제외문자 : '
            TextInput:
                id: excludeTextInput
                hint_text: '제외할 문자를 입력하세요'
        BoxLayout:
            size_hint_y: 0.4
            Label:
                text: '길이 : '
            TextInput:
                id: lengthTextInput
                hint_text: '비밀번호 길이를 입력하세요'
        BoxLayout:
            Button:
                text: '저장'
                on_press: root.saveSettings()
            Button:
                text: '취소'
                on_press: root.manager.current = 'accountList'
